import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

/** The main container that connects our Rails backend and React frontend (DO NOT TOUCH, AUTOGENERATED) */
document.addEventListener("turbo:load", () => {
  const root = createRoot(
    document.body.appendChild(document.createElement("div"))
  );
  root.render(<App />);
});
